[build]
jobs = 1

[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--exclude-all-symbols"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true

[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.test]
opt-level = 0
debug = 1
codegen-units = 1